export const fortunes = [
  // — Classic Wisdom —
  "The obstacle is the way. — Marcus Aurelius",
  "We suffer more in imagination than in reality. — Seneca",
  "It is not because things are difficult that we do not dare. It is because we do not dare that they are difficult. — Seneca",
  "The soul becomes dyed with the color of its thoughts. — Marcus Aurelius",
  "Begin at once to live, and count each separate day as a separate life. — Seneca",
  "What you seek is seeking you. — Rumi",
  "The wound is the place where the light enters you. — Rumi",
  "The cave you fear to enter holds the treasure you seek. — Joseph Campbell",
  "He who has a why to live can bear almost any how. — Nietzsche",
  "Knowing yourself is the beginning of all wisdom. — Aristotle",
  "The unexamined life is not worth living. — Socrates",
  "Nature does not hurry, yet everything is accomplished. — Lao Tzu",
  "When I let go of what I am, I become what I might be. — Lao Tzu",
  "The journey of a thousand miles begins with a single step. — Lao Tzu",
  "Mastering others is strength. Mastering yourself is true power. — Lao Tzu",
  "A disciplined mind brings happiness. — Buddha",
  "What you are is what you have been. What you'll be is what you do now. — Buddha",
  "There is a crack in everything. That's how the light gets in. — Leonard Cohen",
  "Life can only be understood backwards; but it must be lived forwards. — Kierkegaard",
  "Until you make the unconscious conscious, it will direct your life and you will call it fate. — Jung",
  "Let everything happen to you: beauty and terror. Just keep going. No feeling is final. — Rilke",
  "In the middle of difficulty lies opportunity. — Einstein",
  "Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away. — Saint-Exupéry",
  "Be patient toward all that is unsolved in your heart. — Rilke",
  "The privilege of a lifetime is to become who you truly are. — Jung",
  "To live is the rarest thing in the world. Most people exist, that is all. — Wilde",
  "Fortune favors the bold. — Virgil",
  "The happiness of your life depends upon the quality of your thoughts. — Marcus Aurelius",
  "Dwell on the beauty of life. Watch the stars, and see yourself running with them. — Marcus Aurelius",
  "While we wait for life, life passes. — Seneca",
  "There is no easy way from the earth to the stars. — Seneca",

  // — Sharp One-liners —
  "Hard choices, easy life. Easy choices, hard life.",
  "Comparison is the thief of joy.",
  "The map is not the territory.",
  "You do not rise to your goals. You fall to your systems.",
  "Depth beats noise.",
  "Calm is a superpower.",
  "The way out is through.",
  "Pressure makes pearls.",
  "Small hinges swing big doors.",
  "Clarity creates momentum.",
  "What you tolerate becomes your standard.",
  "What you feed grows.",
  "A clear no protects a meaningful yes.",
  "The quiet work matters most.",
  "Most people quit right before the compounding starts.",
  "Real strength is calm under pressure.",
  "The seed grows in darkness.",
  "Every master was once a disaster.",
  "Strong convictions, loosely held.",
  "Keep your word, especially to yourself.",
  "The wise build before they boast.",
  "Most walls are doors in disguise.",
  "Discomfort is the tuition for growth.",
  "You become credible by keeping promises to yourself.",
  "The right path is rarely the crowded one.",
  "A little progress, repeated daily, becomes a different life.",

  // — Playful & Internet-Native —
  "There are two types of people: those who can extrapolate from incomplete data.",
  "If at first you don't succeed, redefine success.",
  "Today's forecast: 100% chance of things happening.",
  "The code works. Ship it before it changes its mind.",
  "Your future self is already proud of you for being here.",
  "The WiFi will be strong wherever you go next.",
  "You are someone's favorite notification.",
  "Plot twist: you were the main character all along.",
  "The universe just winked at you. Did you catch it?",
  "The algorithm is about to work in your favor.",
  "Not all treasure is silver and gold. Some of it is sats.",
  "You're one commit away from something great.",
  "If Plan A fails, remember the alphabet has 25 more letters.",
  "Be the person your dog thinks you are.",
  "Everything is a file if you're brave enough.",
  "Your imposter syndrome is lying to you.",
  "This fortune cost 100 sats. Your smile? Priceless.",
  "Someone, somewhere, is Googling exactly what you know.",

  // — Mystical Fortune-Cookie —
  "A pleasant surprise awaits you before the week ends.",
  "The answer you seek is already within you. Be still.",
  "Something you lost will soon return in a new form.",
  "A door you thought was closed is quietly opening.",
  "The next stranger you speak to carries an important message.",
  "Pay attention to your dreams tonight. They know something.",
  "An old friend is thinking of you at this very moment.",
  "The path will reveal itself when you stop trying to see its end.",
  "A small act of kindness you forgot about is rippling outward.",
  "You are closer than you think. One more step.",
  "The timing isn't late. It's precise.",
  "What feels like the end is only a turn in the road.",
  "Something important is arriving. Make space for it.",
  "Trust the detour. It knows where it's going.",
  "The patience you're practicing now will compound soon.",
  "A decision you've been avoiding will become obvious by morning.",
  "The right people are on their way to you.",

  // — Bitcoin & Lightning —
  "21 million. No more, no less.",
  "Proof of work is truth without permission.",
  "Fix the money, fix the incentives.",
  "Savings are stored time.",
  "Low time preference builds cathedrals.",
  "Sound money makes honest plans possible.",
  "Freedom compounds.",
  "The signal is there for those willing to tune in.",
  "Build quietly. Let the world notice later.",
  "A sovereign mind is hard to manipulate.",
  "Every sat tells a story.",
  "Value for value. It's that simple.",

  // — Deep & Philosophical —
  "The flame that burns twice as bright burns half as long.",
  "The river cuts through rock not because of its power, but because of its persistence.",
  "No tree can grow to heaven unless its roots reach down to hell. — Jung",
  "It is easier to act your way into a new way of thinking than think your way into a new way of acting.",
  "Pain can be a teacher if ego does not interrupt the lesson.",
  "The future is built by those who can delay gratification.",
  "A man who can govern himself needs few rulers.",
  "Conviction is forged when comfort is removed.",
  "The quality of your life is hidden in your habits.",
  "Endurance is a form of intelligence.",
  "What is measured improves. What is cherished endures.",
  "Freedom starts with self-command.",
  "Aim at truth, even when it costs.",
  "Reputation is earned in drops and lost in buckets.",
  "The things worth building usually take longer than you hoped.",
];

export function getRandomFortune(): string {
  return fortunes[Math.floor(Math.random() * fortunes.length)];
}
