import { withPayment } from "@moneydevkit/nextjs/server";

const fortunes = [
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "A ship in harbor is safe, but that is not what ships are built for.",
  "The obstacle is the way.",
  "What you seek is seeking you. — Rumi",
  "He who has a why to live can bear almost any how. — Nietzsche",
  "The only way to do great work is to love what you do. — Steve Jobs",
  "In the middle of difficulty lies opportunity. — Einstein",
  "Fortune favors the bold. — Virgil",
  "The cave you fear to enter holds the treasure you seek. — Joseph Campbell",
  "Not all those who wander are lost. — Tolkien",
  "The wound is the place where the light enters you. — Rumi",
  "We suffer more in imagination than in reality. — Seneca",
  "Memento mori. — Marcus Aurelius",
  "Kites rise highest against the wind, not with it. — Churchill",
  "The best revenge is massive success. — Sinatra",
  "Be yourself; everyone else is already taken. — Oscar Wilde",
  "It is not the mountain we conquer, but ourselves. — Edmund Hillary",
  "The only limit to our realization of tomorrow will be our doubts of today. — FDR",
  "Do not go gentle into that good night. — Dylan Thomas",
  "Everything you can imagine is real. — Picasso",
  "The unexamined life is not worth living. — Socrates",
  "Turn your wounds into wisdom. — Oprah",
  "Stars can't shine without darkness.",
  "A smooth sea never made a skilled sailor.",
  "The man who moves a mountain begins by carrying away small stones. — Confucius",
  "What we think, we become. — Buddha",
  "Life shrinks or expands in proportion to one's courage. — Anaïs Nin",
  "The only impossible journey is the one you never begin. — Tony Robbins",
  "If you want to go fast, go alone. If you want to go far, go together. — African proverb",
  "The diamond cannot be polished without friction. — Confucius",
  "Fall seven times, stand up eight. — Japanese proverb",
  "Where there is no struggle, there is no strength. — Oprah",
  "An uncut gem does not sparkle.",
  "You miss 100% of the shots you don't take. — Gretzky",
  "Luck is what happens when preparation meets opportunity. — Seneca",
  "The bamboo that bends is stronger than the oak that resists. — Japanese proverb",
  "No pressure, no diamonds. — Thomas Carlyle",
  "The dose makes the poison. — Paracelsus",
  "Amor fati — love your fate. — Nietzsche",
  "Be water, my friend. — Bruce Lee",
  "Action is the foundational key to all success. — Picasso",
  "The mind is everything. What you think, you become. — Buddha",
  "It always seems impossible until it's done. — Mandela",
  "He who fears he shall suffer, already suffers what he fears. — Montaigne",
  "Knowledge speaks, but wisdom listens. — Hendrix",
  "To live is the rarest thing in the world. Most people exist, that is all. — Oscar Wilde",
  "In three words I can sum up everything I've learned about life: it goes on. — Robert Frost",
  "The quieter you become, the more you can hear. — Ram Dass",
  "We are what we repeatedly do. Excellence is not an act, but a habit. — Aristotle",
  "21 million. No more, no less. — Satoshi Nakamoto",

  "Make each day your masterpiece. — John Wooden",
  "Do the thing and you will have the power. — Emerson",
  "Energy and persistence conquer all things. — Benjamin Franklin",
  "Discipline is destiny. — Heraclitus",
  "The impediment to action advances action. — Marcus Aurelius",
  "How you do anything is how you do everything.",
  "A man cannot step into the same river twice. — Heraclitus",
  "To begin, begin. — William Wordsworth",
  "First say to yourself what you would be; then do what you have to do. — Epictetus",
  "Do not pray for an easy life. Pray for the strength to endure a difficult one. — Bruce Lee",
  "Waste no more time arguing what a good man should be. Be one. — Marcus Aurelius",
  "Man is made by his belief. As he believes, so he is.",
  "No man ever steps in the same river twice, for it is not the same river and he is not the same man. — Heraclitus",
  "Happiness depends upon ourselves. — Aristotle",
  "The soul becomes dyed with the color of its thoughts. — Marcus Aurelius",
  "If it is endurable, then endure it. Stop complaining. — Marcus Aurelius",
  "Difficulties strengthen the mind, as labor does the body. — Seneca",
  "Begin at once to live, and count each separate day as a separate life. — Seneca",
  "He who is brave is free. — Seneca",
  "No great thing is created suddenly. — Epictetus",
  "Circumstances don't make the man, they only reveal him. — Epictetus",
  "The greater the difficulty, the more glory in surmounting it. — Epicurus",
  "Do not spoil what you have by desiring what you have not. — Epicurus",
  "The sun shines on all alike. — Heraclitus",
  "Character is fate. — Heraclitus",
  "Well begun is half done. — Aristotle",
  "Patience is bitter, but its fruit is sweet. — Aristotle",
  "Knowing yourself is the beginning of all wisdom. — Aristotle",
  "No act of kindness, no matter how small, is ever wasted. — Aesop",
  "The fox has many tricks. The hedgehog has but one. But that is the best of all. — Archilochus",
  "A gem cannot be polished without friction, nor a man perfected without trials.",
  "Great things are not done by impulse, but by a series of small things brought together. — Van Gogh",
  "What is now proved was once only imagined. — William Blake",
  "The bird fights its way out of the egg. The egg is the world. — Hesse",
  "Who looks outside, dreams; who looks inside, awakes. — Jung",
  "Until you make the unconscious conscious, it will direct your life and you will call it fate. — Jung",
  "I am not what happened to me, I am what I choose to become. — Jung",
  "The privilege of a lifetime is to become who you truly are. — Jung",
  "He who has a strong enough why can bear almost any how.",
  "To dare is to lose one's footing momentarily. Not to dare is to lose oneself. — Kierkegaard",
  "Life can only be understood backwards; but it must be lived forwards. — Kierkegaard",
  "The most common form of despair is not being who you are. — Kierkegaard",
  "No tree, it is said, can grow to heaven unless its roots reach down to hell. — Jung",
  "He who has health has hope, and he who has hope has everything.",
  "Act as if what you do makes a difference. It does. — William James",
  "The greatest weapon against stress is our ability to choose one thought over another. — William James",
  "Believe and act as if it were impossible to fail. — Charles Kettering",
  "If opportunity doesn't knock, build a door. — Milton Berle",
  "Do what you can, with what you have, where you are. — Theodore Roosevelt",
  "Far and away the best prize that life offers is the chance to work hard at work worth doing. — Theodore Roosevelt",
  "Comparison is the thief of joy. — Theodore Roosevelt",
  "It is hard to fail, but it is worse never to have tried to succeed. — Theodore Roosevelt",
  "Nothing in the world is worth having or worth doing unless it means effort, pain, difficulty. — Theodore Roosevelt",
  "Success is stumbling from failure to failure with no loss of enthusiasm. — Churchill",
  "If you're going through hell, keep going. — Churchill",
  "Courage is what it takes to stand up and speak; courage is also what it takes to sit down and listen. — Churchill",
  "The future depends on what you do today. — Gandhi",
  "Strength does not come from physical capacity. It comes from an indomitable will. — Gandhi",
  "Satisfaction lies in the effort, not in the attainment. — Gandhi",
  "Live as if you were to die tomorrow. Learn as if you were to live forever. — Gandhi",
  "An ounce of practice is worth more than tons of preaching. — Gandhi",
  "He who has overcome his fears will truly be free. — Aristotle",
  "There is no easy way from the earth to the stars. — Seneca",
  "Fire tests gold, suffering tests brave men. — Seneca",
  "True happiness is to enjoy the present, without anxious dependence upon the future. — Seneca",
  "As long as you live, keep learning how to live. — Seneca",
  "Luck is where the prepared mind meets opportunity.",
  "Do every act of your life as though it were the very last act of your life. — Marcus Aurelius",
  "You have power over your mind, not outside events. Realize this, and you will find strength. — Marcus Aurelius",
  "The happiness of your life depends upon the quality of your thoughts. — Marcus Aurelius",
  "Never let the future disturb you. You will meet it, if you have to, with the same weapons of reason which today arm you against the present. — Marcus Aurelius",
  "Very little is needed to make a happy life. — Marcus Aurelius",
  "What stands in the way becomes the way. — Marcus Aurelius",
  "Be tolerant with others and strict with yourself. — Marcus Aurelius",
  "A blazing fire makes flame and brightness out of everything thrown into it. — Marcus Aurelius",
  "Dwell on the beauty of life. Watch the stars, and see yourself running with them. — Marcus Aurelius",
  "The greater part of what we say and do is unnecessary. — Marcus Aurelius",
  "To bear trials with a calm mind robs misfortune of its strength. — Seneca",
  "It is not because things are difficult that we do not dare. It is because we do not dare that they are difficult. — Seneca",
  "While we wait for life, life passes. — Seneca",
  "Every new beginning comes from some other beginning's end. — Seneca",
  "No man is more unhappy than he who never faces adversity. — Seneca",
  "The brave man is not he who does not feel afraid, but he who conquers that fear. — Nelson Mandela",
  "May your choices reflect your hopes, not your fears. — Nelson Mandela",
  "Resentment is like drinking poison and hoping it will kill your enemies. — Nelson Mandela",
  "There is nothing noble in being superior to your fellow man; true nobility is being superior to your former self. — Hemingway",
  "Courage is grace under pressure. — Hemingway",
  "The world breaks everyone, and afterward, some are strong at the broken places. — Hemingway",
  "We become what we behold. We shape our tools and thereafter our tools shape us. — McLuhan",
  "The future belongs to those who prepare for it today. — Malcolm X",
  "Power concedes nothing without a demand. It never did and it never will. — Frederick Douglass",
  "Without struggle, there is no progress. — Frederick Douglass",
  "If there is no struggle, there is no progress. — Frederick Douglass",
  "Start where you are. Use what you have. Do what you can. — Arthur Ashe",
  "One important key to success is self-confidence. An important key to self-confidence is preparation. — Arthur Ashe",
  "Do not wait to strike till the iron is hot; but make it hot by striking. — William Butler Yeats",
  "Education is not the filling of a pail, but the lighting of a fire. — Yeats",
  "There are no strangers here; only friends you haven't yet met. — Yeats",
  "The world is full of magic things, patiently waiting for our senses to grow sharper. — Yeats",
  "The journey of a thousand miles begins with a single step. — Lao Tzu",
  "Nature does not hurry, yet everything is accomplished. — Lao Tzu",
  "Mastering others is strength. Mastering yourself is true power. — Lao Tzu",
  "A good traveler has no fixed plans and is not intent on arriving. — Lao Tzu",
  "He who knows that enough is enough will always have enough. — Lao Tzu",
  "When I let go of what I am, I become what I might be. — Lao Tzu",
  "Silence is a source of great strength. — Lao Tzu",
  "Knowing others is intelligence; knowing yourself is true wisdom. — Lao Tzu",
  "The flame that burns twice as bright burns half as long.",
  "Pressure makes pearls.",
  "The strongest steel is forged in the hottest fire.",
  "The deeper the roots, the stronger the tree.",
  "You do not find the way. You make it.",
  "Small hinges swing big doors.",
  "Hard choices, easy life. Easy choices, hard life.",
  "The price of greatness is responsibility. — Churchill",
  "A man with outward courage dares to die; a man with inner courage dares to live. — Lao Tzu",
  "To shine your brightest light is to be who you truly are. — Roy T. Bennett",
  "Do not fear being slow. Fear only standing still.",
  "The river cuts through rock not because of its power, but because of its persistence.",
  "If you are going through a storm, keep walking.",
  "The seed grows in darkness.",
  "Every master was once a disaster.",
  "Discomfort is the tuition for growth.",
  "Calm is a superpower.",
  "The way out is through.",
  "A disciplined mind brings happiness. — Buddha",
  "Peace comes from within. Do not seek it without. — Buddha",
  "Thousands of candles can be lit from a single candle, and the life of the candle will not be shortened. — Buddha",
  "Better than a thousand hollow words is one word that brings peace. — Buddha",
  "Work out your own salvation with diligence. — Buddha",
  "What you are is what you have been. What you'll be is what you do now. — Buddha",
  "Your work is to discover your work and then with all your heart to give yourself to it. — Buddha",
  "Endure and persist; this pain will turn to good by and by. — Ovid",
  "Dripping water hollows out stone, not through force but through persistence. — Ovid",
  "He conquers who endures. — Persius",
  "A bend in the road is not the end of the road unless you fail to make the turn.",
  "The comeback is always stronger than the setback.",
  "One day or day one. You decide.",
  "If not now, when? — Hillel",
  "If I am not for myself, who will be for me? If I am only for myself, what am I? If not now, when? — Hillel",
  "You are the sky. Everything else is just the weather. — Pema Chödrön",
  "Let everything happen to you: beauty and terror. Just keep going. No feeling is final. — Rilke",
  "Live the questions now. — Rilke",
  "Perhaps everything terrible is in its deepest being something helpless that wants help from us. — Rilke",
  "Be patient toward all that is unsolved in your heart. — Rilke",
  "Try not to resist life's changes. Let life flow through you. — Rumi",
  "When the soul lies down in that grass, the world is too full to talk about. — Rumi",
  "Raise your words, not your voice. It is rain that grows flowers, not thunder. — Rumi",
  "Why do you stay in prison when the door is so wide open? — Rumi",
  "Set your life on fire. Seek those who fan your flames. — Rumi",
  "Wherever you are, and whatever you do, be in love. — Rumi",
  "Let the beauty of what you love be what you do. — Rumi",
  "When you go through a hard period, when everything seems to oppose you, when you feel you cannot even endure one more minute, never give up then. — Rumi",
  "There is a crack in everything. That's how the light gets in. — Leonard Cohen",
  "Ring the bells that still can ring. — Leonard Cohen",
  "The simple things are also the most extraordinary things, and only the wise can see them. — Paulo Coelho",
  "One is loved because one is loved. No reason is needed for loving. — Paulo Coelho",
  "When we strive to become better than we are, everything around us becomes better too. — Paulo Coelho",
  "Tough times never last, but tough people do. — Robert Schuller",
  "Problems are not stop signs, they are guidelines. — Robert Schuller",
  "The future starts today, not tomorrow. — Pope John Paul II",
  "The harder the conflict, the more glorious the triumph. — Thomas Paine",
  "These are the days that must happen to you. — Walt Whitman",
  "Keep your face always toward the sunshine, and shadows will fall behind you. — Walt Whitman",
  "Be curious, not judgmental. — Walt Whitman",
  "I exist as I am, that is enough. — Walt Whitman",
  "Happiness is not by chance, but by choice. — Jim Rohn",
  "Either you run the day or the day runs you. — Jim Rohn",
  "Discipline is the bridge between goals and accomplishment. — Jim Rohn",
  "Motivation is what gets you started. Habit is what keeps you going. — Jim Ryun",
  "The secret of getting ahead is getting started. — Mark Twain",
  "The two most important days in your life are the day you are born and the day you find out why. — Mark Twain",
  "Courage is resistance to fear, mastery of fear, not absence of fear. — Mark Twain",
  "To improve is to change; to be perfect is to change often. — Churchill",
  "Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away. — Antoine de Saint-Exupéry",
  "He who would learn to fly one day must first learn to stand and walk and run and climb and dance. — Nietzsche",
  "Become who you are. — Nietzsche",
  "And those who were seen dancing were thought to be insane by those who could not hear the music. — Nietzsche",
  "One must still have chaos in oneself to be able to give birth to a dancing star. — Nietzsche",
  "The individual has always had to struggle to keep from being overwhelmed by the tribe. — Nietzsche",
  "No price is too high to pay for the privilege of owning yourself. — Nietzsche",
  "He who has a why to live can bear almost any how. — Nietzsche",
  "There are no beautiful surfaces without a terrible depth. — Nietzsche",
  "The future influences the present just as much as the past. — Nietzsche",
  "Satoshi's genius was removing the need for trust.",
  "Proof of work is truth without permission.",
  "Fix the money, fix the incentives.",
  "Savings are stored time.",
  "Low time preference builds cathedrals.",
  "Sound money makes honest plans possible.",
  "Freedom compounds.",
  "Truth does not need a marketing department.",
  "The signal is there for those willing to tune in.",
  "Build quietly. Let the world notice later.",
  "The reward for good work is more good work.",
  "Nothing valuable is built without patience.",
  "Attention is a form of life.",
  "Guard your inputs and your life will change.",
  "What you repeat, you reinforce.",
  "What you tolerate becomes your standard.",
  "Reputation is earned in drops and lost in buckets.",
  "Clarity creates momentum.",
  "A clean conscience sleeps well.",
  "The things worth building usually take longer than you hoped.",
  "The right path is rarely the crowded one.",
  "You become credible by keeping promises to yourself.",
  "Pain can be a teacher if ego does not interrupt the lesson.",
  "Most people quit right before the compounding starts.",
  "It is easier to act your way into a new way of thinking than think your way into a new way of acting.",
  "A man who can govern himself needs few rulers.",
  "The future is built by those who can delay gratification.",
  "Conviction is forged when comfort is removed.",
  "If you want a new life, build new days.",
  "The quality of your life is hidden in your habits.",
  "Strong convictions, loosely held.",
  "The quiet work matters most.",
  "Freedom starts with self-command.",
  "Aim at truth, even when it costs.",
  "The map is not the territory.",
  "What is measured improves. What is cherished endures.",
  "A life of drift ends in regret.",
  "A little progress, repeated daily, becomes a different life.",
  "Most walls are doors in disguise.",
  "Keep your word, especially to yourself.",
  "Depth beats noise.",
  "Real strength is calm under pressure.",
  "A clear no protects a meaningful yes.",
  "What you feed grows.",
  "You do not rise to your goals. You fall to your systems.",
  "The wise build before they boast.",
  "Endurance is a form of intelligence.",
  "The man who can wait has an advantage.",
  "A sovereign mind is hard to manipulate."
];

const handler = async () => {
  const fortune = fortunes[Math.floor(Math.random() * fortunes.length)];
  return Response.json({
    fortune,
    timestamp: new Date().toISOString(),
  });
};

export const GET = withPayment({ amount: 10, currency: "SAT" }, handler);
