import { getRandomFortune, type Rarity } from "@/lib/fortunes";
import { isPaid } from "@/lib/payment-store";
import { getRedis } from "@/lib/redis";
import { checkRateLimit } from "@/lib/ratelimit";
import { getOrCreateDeviceId, attachDeviceCookie, resolveDisplayNameFromReq } from "@/lib/device-id";
import { recordFortuneOnce } from "@/lib/idempotency";
import { getFlags, unavailableResponse } from "@/lib/flags";

const CLAIM_TTL = 86_400; // 24 hours
const FORTUNE_TTL = 86_400; // 24 hours

/**
 * Fallback fortune endpoint for when the MDK webhook flow is broken
 * (LDK node sync timeout on Vercel Serverless). The user has already
 * paid MDK — this just delivers the fortune they're owed.
 *
 * Protected by requiring a valid paymentHash that was issued during
 * the L402 flow. Claims are tracked in Redis to prevent replay.
 *
 * Fortune consistency: uses the same fortune:{paymentHash} cache as
 * /fortune/status so the same paymentHash always returns the same fortune.
 */
export async function GET(req: Request) {
  const { fortuneSingleEnabled } = getFlags();
  if (!fortuneSingleEnabled) return unavailableResponse("Fortunes");
  const limited = await checkRateLimit(req, { prefix: "claim", limit: 5, window: "1 m" });
  if (limited) return limited;

  const url = new URL(req.url);
  const paymentHash = url.searchParams.get("paymentHash");

  // Require a payment hash
  if (!paymentHash || !/^[a-fA-F0-9]{64}$/.test(paymentHash)) {
    return Response.json(
      { error: { code: "invalid_param", message: "Valid paymentHash is required" } },
      { status: 400 },
    );
  }

  // Verify payment was actually made — fail closed
  let paid: boolean;
  try {
    paid = await isPaid(paymentHash);
  } catch (e) {
    console.error("[fortune/claim:isPaid]", e);
    return Response.json(
      { error: { code: "service_unavailable", message: "Payment verification temporarily unavailable. Please retry." } },
      { status: 503 },
    );
  }

  if (!paid) {
    return Response.json(
      { error: { code: "payment_required", message: "No payment found for this hash" } },
      { status: 402 },
    );
  }

  // Check if already claimed via Redis (cross-instance safe)
  const redis = getRedis();
  if (!redis) {
    return Response.json(
      { error: { code: "service_unavailable", message: "Claim service temporarily unavailable. Please retry." } },
      { status: 503 },
    );
  }

  // Atomically claim via SET NX — only one request wins
  try {
    const acquired = await redis.set(`claim:${paymentHash}`, Date.now(), {
      nx: true,
      ex: CLAIM_TTL,
    });
    if (!acquired) {
      // Already claimed — return the cached fortune for consistency
      const cached = await redis.get<{ fortune: string; rarity?: Rarity; timestamp: string }>(
        `fortune:${paymentHash}`,
      );
      if (cached) {
        return Response.json({
          fortune: cached.fortune,
          rarity: cached.rarity ?? "common",
          timestamp: cached.timestamp,
          verified: true,
        });
      }
      return Response.json(
        { error: { code: "already_claimed", message: "This payment has already been claimed" } },
        { status: 409 },
      );
    }
  } catch (e) {
    console.error("[fortune/claim:setNX]", e);
    return Response.json(
      { error: { code: "service_unavailable", message: "Claim service temporarily unavailable. Please retry." } },
      { status: 503 },
    );
  }

  // Check fortune cache first (may have been generated by /fortune/status)
  let fortune: string;
  let rarity: Rarity;
  let timestamp: string;

  try {
    const cached = await redis.get<{ fortune: string; rarity?: Rarity; timestamp: string }>(
      `fortune:${paymentHash}`,
    );
    if (cached) {
      fortune = cached.fortune;
      rarity = cached.rarity ?? "common";
      timestamp = cached.timestamp;
    } else {
      // Generate and cache — same paymentHash will return this fortune everywhere
      const f = getRandomFortune();
      fortune = f.text;
      rarity = f.rarity;
      timestamp = new Date().toISOString();
      await redis.set(`fortune:${paymentHash}`, { fortune, rarity, timestamp }, { ex: FORTUNE_TTL });
    }
  } catch (e) {
    console.error("[fortune/claim:fortuneCache]", e);
    // Cache failure — generate ephemeral fortune (best effort)
    const f = getRandomFortune();
    fortune = f.text;
    rarity = f.rarity;
    timestamp = new Date().toISOString();
  }

  const { deviceId, isNew } = getOrCreateDeviceId(req);
  const displayName = resolveDisplayNameFromReq(req, deviceId);

  // Record once (Redis SET NX — safe if /fortune/status already recorded)
  await recordFortuneOnce(paymentHash, deviceId, displayName, rarity, 100);

  const res = Response.json({
    fortune,
    rarity,
    timestamp,
    verified: true,
  });
  if (isNew) attachDeviceCookie(res, deviceId);
  return res;
}
